modLoader="javafml"
loaderVersion="[33,)"
license="MIT"
[[mods]]
modId="behgameon"
version="${file.jarVersion}"
displayName="Behgameon"
displayURL="https://www.curseforge.com/minecraft/mc-mods/behgameon"
credits="DEMMERS"
authors="AzureDoomC"
description='''
Adds the custom items to the Behgameon Modpack.
'''